{% set version = "2020.07" %}
{% set name = "uptune" %}
{% set gcc_linux_ver = '7.2.0' %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  path: ../
  # git_url: https://github.com/cornell-zhang/heterocl.git
  # git_tag: master

build:
  entry_points:
    - ut = uptune.on:main

requirements:
  build:
    - cmake
    - make
    - python
  run:
    - python
    - xgboost
    - argparse
    - future
    - jinja2
    - pandas
    - SQLAlchemy>=0.8.2
    - sympy
    - scikit-learn
    - matplotlib 
    - psutil 
    - setproctitle
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('matplotlib') }}

# test:
#   commands:
#     - ut -h
#   imports:
#     - uptune
#     - uptune.on

about:
  home: https://github.com/cornell-zhang/uptune
  license: BSD-3
